import type { Report } from '@huellita/shared';

export const mockReports: Report[] = [
  {
    id: '1a2b3c4d-0000-0000-0000-000000000001',
    type: 'lost',
    status: 'active',
    pet: {
      id: 'pet-0001',
      name: 'Luna',
      species: 'dog',
      breed: 'Labrador',
      color: 'Negro',
      size: 'large',
      description: 'Muy amigable, collar rojo con plaquita',
      photos: ['https://picsum.photos/seed/dog1/400/300'],
      microchip: null,
    },
    location: {
      lat: -34.5889,
      lng: -58.4163,
      address: 'Av. Santa Fe 3200',
      neighborhood: 'Palermo',
      city: 'Buenos Aires',
      province: 'Buenos Aires',
    },
    contactName: 'María García',
    contactPhone: '+5491112345678',
    contactEmail: 'maria@example.com',
    description:
      'Se perdió el martes cerca del Parque Tres de Febrero. Es muy amigable y le gustan los niños. Lleva collar rojo con plaquita que dice "Luna".',
    userId: 'user-001',
    createdAt: '2026-04-30T14:00:00Z',
    updatedAt: '2026-04-30T14:00:00Z',
    resolvedAt: null,
  },
  {
    id: '1a2b3c4d-0000-0000-0000-000000000002',
    type: 'found',
    status: 'active',
    pet: {
      id: 'pet-0002',
      name: null,
      species: 'cat',
      breed: 'Común europeo',
      color: 'Naranja y blanco',
      size: 'medium',
      description: 'Muy asustado, se esconde debajo de autos',
      photos: ['https://picsum.photos/seed/cat2/400/300'],
      microchip: null,
    },
    location: {
      lat: -34.5874,
      lng: -58.3941,
      address: 'Av. Alvear 1800',
      neighborhood: 'Recoleta',
      city: 'Buenos Aires',
      province: 'Buenos Aires',
    },
    contactName: 'Carlos López',
    contactPhone: '+5491198765432',
    contactEmail: null,
    description:
      'Encontré este gatito en la puerta de mi edificio. Parece perdido y tiene hambre. No tiene collar. Lo tengo resguardado.',
    userId: 'user-002',
    createdAt: '2026-05-01T09:30:00Z',
    updatedAt: '2026-05-01T09:30:00Z',
    resolvedAt: null,
  },
  {
    id: '1a2b3c4d-0000-0000-0000-000000000003',
    type: 'sighting',
    status: 'active',
    pet: {
      id: 'pet-0003',
      name: 'Max',
      species: 'dog',
      breed: 'Beagle',
      color: 'Tricolor',
      size: 'medium',
      description: 'Corría solo por la vereda, sin collar',
      photos: ['https://picsum.photos/seed/dog3/400/300'],
      microchip: null,
    },
    location: {
      lat: -34.6208,
      lng: -58.3731,
      address: 'Defensa 900',
      neighborhood: 'San Telmo',
      city: 'Buenos Aires',
      province: 'Buenos Aires',
    },
    contactName: 'Ana Martínez',
    contactPhone: '+5491123456789',
    contactEmail: 'ana@example.com',
    description:
      'Vi un beagle tricolor corriendo solo por San Telmo cerca del mercado. Parecía asustado y sin dueño. No pude acercarme.',
    userId: 'user-003',
    createdAt: '2026-05-02T16:15:00Z',
    updatedAt: '2026-05-02T16:15:00Z',
    resolvedAt: null,
  },
  {
    id: '1a2b3c4d-0000-0000-0000-000000000004',
    type: 'lost',
    status: 'active',
    pet: {
      id: 'pet-0004',
      name: 'Michi',
      species: 'cat',
      breed: null,
      color: 'Gris atigrado',
      size: 'small',
      description: 'Muy tímido con extraños, tiene manchita blanca en la nariz',
      photos: ['https://picsum.photos/seed/cat4/400/300'],
      microchip: null,
    },
    location: {
      lat: -34.5598,
      lng: -58.4544,
      address: 'Virrey del Pino 2400',
      neighborhood: 'Belgrano',
      city: 'Buenos Aires',
      province: 'Buenos Aires',
    },
    contactName: 'Roberto Sánchez',
    contactPhone: '+5491187654321',
    contactEmail: null,
    description:
      'Se escapó por la ventana el lunes a la noche. Es muy asustadizo. Tiene una manchita blanca pequeña en la punta de la nariz.',
    userId: 'user-004',
    createdAt: '2026-05-01T22:00:00Z',
    updatedAt: '2026-05-01T22:00:00Z',
    resolvedAt: null,
  },
  {
    id: '1a2b3c4d-0000-0000-0000-000000000005',
    type: 'found',
    status: 'active',
    pet: {
      id: 'pet-0005',
      name: null,
      species: 'dog',
      breed: 'Mestizo',
      color: 'Marrón',
      size: 'medium',
      description: 'Dócil y bien cuidado, tiene collar sin plaquita',
      photos: ['https://picsum.photos/seed/dog5/400/300'],
      microchip: null,
    },
    location: {
      lat: -34.6183,
      lng: -58.4394,
      address: 'Av. Rivadavia 5600',
      neighborhood: 'Caballito',
      city: 'Buenos Aires',
      province: 'Buenos Aires',
    },
    contactName: 'Laura Fernández',
    contactPhone: '+5491156789012',
    contactEmail: 'laura@example.com',
    description:
      'Encontré este perrito marrón en la puerta de la plaza. Tiene collar pero sin plaquita. Parece bien cuidado y entrenado. Lo tengo en casa.',
    userId: 'user-005',
    createdAt: '2026-05-03T11:00:00Z',
    updatedAt: '2026-05-03T11:00:00Z',
    resolvedAt: null,
  },
  {
    id: '1a2b3c4d-0000-0000-0000-000000000006',
    type: 'lost',
    status: 'active',
    pet: {
      id: 'pet-0006',
      name: 'Coco',
      species: 'bird',
      breed: 'Cotorra',
      color: 'Verde y amarillo',
      size: 'small',
      description: 'Dice su nombre y algunas palabras, muy sociable',
      photos: ['https://picsum.photos/seed/bird6/400/300'],
      microchip: null,
    },
    location: {
      lat: -34.5991,
      lng: -58.4436,
      address: 'Av. Corrientes 4800',
      neighborhood: 'Villa Crespo',
      city: 'Buenos Aires',
      province: 'Buenos Aires',
    },
    contactName: 'Daniela Torres',
    contactPhone: '+5491145678901',
    contactEmail: 'daniela@example.com',
    description:
      'Se voló por la ventana abierta el domingo. Es una cotorra verde y amarilla que dice su nombre "Coco" y algunas palabras. Muy dócil y sociable.',
    userId: 'user-006',
    createdAt: '2026-05-04T08:00:00Z',
    updatedAt: '2026-05-04T08:00:00Z',
    resolvedAt: null,
  },
];

export function getMockReport(id: string): Report | undefined {
  return mockReports.find((r) => r.id === id);
}
